# code: language=ansible

---
- name: Register ~/.gitconfig user.name and user.email
  community.general.git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_user }}"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add switch alias to ~/.gitconfig
  community.general.git_config:
    name: alias.switch
    scope: global
    value: "!legit switch"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add sync alias to ~/.gitconfig
  community.general.git_config:
    name: alias.sync
    scope: global
    value: "!legit sync"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Add publish alias to ~/.gitconfig
  community.general.git_config:
    name: alias.publish
    scope: global
    value: "!legit publish"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add unpublish alias to ~/.gitconfig
  community.general.git_config:
    name: alias.unpublish
    scope: global
    value: "!legit unpublish"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add undo alias to ~/.gitconfig
  community.general.git_config:
    name: alias.undo
    scope: global
    value: "!legit undo"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add branches alias to ~/.gitconfig
  community.general.git_config:
    name: alias.branches
    scope: global
    value: "!legit branches"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add parent alias to ~/.gitconfig
  community.general.git_config:
    name: alias.parent
    scope: global
    value: "!git show-branch | grep '*' | grep -v \"$(git rev-parse --abbrev-ref HEAD)\" | head -n1 | sed 's/.*\\[\\(.*\\)\\].*/\\1/' | sed 's/[\\^~].*//'"
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add amend alias to ~/.gitconfig
  community.general.git_config:
    name: alias.amend
    scope: global
    value: commit --amend --no-edit
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: git

- name: Add a setting to ~/.gitconfig
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
  tags: git
