# code: language=ansible

---
- name: Download asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ home_dir }}/.asdf"
    version: v0.13.1
    force: true
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Add asdf plugins
  ansible.builtin.shell: |
    source {{ home_dir }}/.asdf/asdf.sh
    asdf plugin-add {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - awscli https://github.com/MetricMike/asdf-awscli.git
    - gcloud https://github.com/jthegedus/asdf-gcloud
    - golang https://github.com/kennyp/asdf-golang.git
    - helm https://github.com/Antiarchitect/asdf-helm.git
    - helmfile https://github.com/nwiizo/asdf-helmfile.git
    - kubectl https://github.com/asdf-community/asdf-kubectl.git
    - kubectx https://github.com/virtualstaticvoid/asdf-kubectx.git
    - kustomize https://github.com/Banno/asdf-kustomize.git
    - lazydocker https://github.com/comdotlinux/asdf-lazydocker.git
    - lazygit https://github.com/nklmilojevic/asdf-lazygit.git
    - mongodb https://github.com/sylph01/asdf-mongodb.git
    - nodejs https://github.com/asdf-vm/asdf-nodejs.git
    - packer https://github.com/asdf-community/asdf-hashicorp.git
    - poetry https://github.com/asdf-community/asdf-poetry.git
    - python
    - ruby
    - rust https://github.com/asdf-community/asdf-rust.git
    - terraform https://github.com/asdf-community/asdf-hashicorp.git
    - vault https://github.com/asdf-community/asdf-hashicorp.git
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Install latest runtime
  ansible.builtin.shell: |
    source {{ home_dir }}/.asdf/asdf.sh
    asdf install {{ item }} latest
    asdf global {{ item }} latest
  args:
    executable: /bin/bash
  with_items:
    - awscli
    - gcloud
    - golang
    - helm
    - helmfile
    - kubectl
    - kubectx
    - kustomize
    - lazydocker
    - mongodb
    - nodejs
    - packer
    - poetry
    - python
    - ruby
    - rust
    - terraform
    - vault
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Reshim runtimes
  ansible.builtin.shell: |
    source {{ home_dir }}/.asdf/asdf.sh
    asdf reshim
  args:
    executable: /bin/bash
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Set poetry options
  ansible.builtin.shell: |
    poetry config virtualenvs.prefer-active-python true
    poetry config virtualenvs.in-project true
    poetry config virtualenvs.create true
    poetry config warnings.export false
  args:
    executable: /bin/bash
  become: false
  become_user: "{{ ansible_env.SUDO_USER }}"
